# Generated by Django 4.2.7 on 2023-11-23 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 23, 20, 40, 58, 477777)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='idade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
